import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Student Managment",
  description: "Generated by Student Managment",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dracula">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.com/libraries/Chart.js" />
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body>
        <main>{children}</main>
        {/* </div> */}

        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <script src="https://www.jsdelivr.com/package/npm/chart.js?path=dist"></script>
      </body>
    </html>
  );
}
